apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lunch
resources:
  - namespace.yaml
  - backend-deploy.yaml
  - backend-svc.yaml
  - frontend-deploy.yaml
  - frontend-svc.yaml
images:
  - name: docker.io/yangjiwoogn/lunch-backend
    newTag: becb820ce05c5b1785be7410e1ea0dcb81aa8267
  - name: docker.io/yangjiwoogn/lunch-frontend
    newTag: becb820ce05c5b1785be7410e1ea0dcb81aa8267
